opencast/opencast-docker

docker-compose/docker-compose.allinone.hsql.yml
docker-compose/docker-compose.allinone.mariadb.yml
docker-compose/docker-compose.multiserver.mariadb.yml

This changes the configured Opencast hostname from opencast to localhost. Running `docker-machine` one would need to change the hostname to point to the virtual machine as is stated in the README.

Change default hostname in compose files

---

docker-compose/README.md
docker-compose/docker-compose.multiserver.mariadb.yml

I've created a workaround that will allow you to start a multiserver setup with docker-compose without too much work. A detailed explanation why it is needed and how it works can be found in `docker-compose/README.md`.

Fix for multiserver docker-compose problems with hostnames.

---

Dockerfiles/admin/Dockerfile
Dockerfiles/adminworker/Dockerfile
Dockerfiles/allinone/Dockerfile
Dockerfiles/build/Dockerfile
Dockerfiles/ingest/Dockerfile
Dockerfiles/presentation/Dockerfile
Dockerfiles/worker/Dockerfile

Alpine new provides a installable tesseract package. Own compilation is now no longer necessary.

Use tesseract-ocr package instead of compiling it

---

Dockerfiles/admin/Dockerfile
Dockerfiles/admin/assets/docker-healthcheck.sh
Dockerfiles/adminworker/Dockerfile
Dockerfiles/adminworker/assets/docker-healthcheck.sh
Dockerfiles/allinone/Dockerfile
Dockerfiles/allinone/assets/docker-healthcheck.sh
Dockerfiles/build/Dockerfile
Dockerfiles/ingest/Dockerfile
Dockerfiles/ingest/assets/docker-healthcheck.sh
Dockerfiles/presentation/Dockerfile
Dockerfiles/presentation/assets/docker-healthcheck.sh
Dockerfiles/worker/Dockerfile
Dockerfiles/worker/assets/docker-healthcheck.sh

The HEALTHCHECK could not run before as the `curl` command was missing. Also the HTTP status check now not only looks for `204` but for any `2xx`.

Add missing curl and check HTTP status code in 2xx range

---

Dockerfiles/build/assets/bin/is_git_repo
Dockerfiles/build/assets/bin/is_oc_dist
Dockerfiles/build/assets/bin/is_oc_installed
Dockerfiles/build/assets/bin/oc_clean_data
Dockerfiles/build/assets/bin/oc_install
Dockerfiles/build/assets/bin/oc_uninstall

This fixes various small errors in scripts of the build image:
* remove `set -e` were a failure should not stop the script
* replace falsely used `return` with `exit`
* cleaning of directories has not matched any file before (nothing was removed)
* during install some folders were not yet created
To verify run these commands from the root of this repository:
```sh
$ make build-build
$ export OPENCAST_SRC=$(mktemp -d)
$ docker-compose -p opencast-build -f docker-compose/docker-compose.build.yml up -d
$ docker-compose -p opencast-build -f docker-compose/docker-compose.build.yml exec opencast bash
$ oc_clone
$ oc_build
$ oc_install allinone
$ oc_run
$ oc_uninstall
$ oc_clean_data
$ exit
$ docker-compose -p opencast-build -f docker-compose/docker-compose.build.yml down -v
$ sudo rm -rf …
```

Fix various build script errors

---

Dockerfiles/admin/assets/docker-healthcheck.sh
Dockerfiles/adminpresentation/assets/docker-healthcheck.sh
Dockerfiles/adminworker/assets/docker-healthcheck.sh
Dockerfiles/allinone/assets/docker-healthcheck.sh
Dockerfiles/ingest/assets/docker-healthcheck.sh
Dockerfiles/presentation/assets/docker-healthcheck.sh
Dockerfiles/worker/assets/docker-healthcheck.sh
test/suite.bats

This fixes:
* wrong path
* shellcheck linting error with `$?` variable
* additional output is written to `/dev/null`
* differences between the distributions
in the `docker-healthcheck.sh` script.

Fix error in healthcheck script

---

Dockerfiles/admin/Dockerfile
Dockerfiles/admin/assets/docker-entrypoint.sh
Dockerfiles/adminpresentation/Dockerfile
Dockerfiles/adminpresentation/assets/docker-entrypoint.sh
Dockerfiles/adminworker/Dockerfile
Dockerfiles/adminworker/assets/docker-entrypoint.sh
Dockerfiles/allinone/Dockerfile
Dockerfiles/allinone/assets/docker-entrypoint.sh
Dockerfiles/build/assets/build/docker-entrypoint.sh
Dockerfiles/ingest/Dockerfile
Dockerfiles/ingest/assets/docker-entrypoint.sh
Dockerfiles/presentation/Dockerfile
Dockerfiles/presentation/assets/docker-entrypoint.sh
Dockerfiles/worker/Dockerfile
Dockerfiles/worker/assets/docker-entrypoint.sh

Opencast currently does not handle `SIGTERM` and `SIGINT` gracefully. Instead it comes with a `stop-opencast` script. This pull request sets up a `trap` in the entrypoint shell script to handle these signals to execute the stop script.

Add gracefull stop handler

---

.travis.yml
Makefile

Docker 1.13 allows to specify an image to be used as build cache. This should speed up Travis CI builds.
I could not efficiently test this as Travis currently has some API problems causing empty logs.

Add --cache-from to Travis CI script to speed up builds

---

Dockerfiles/admin/Dockerfile
Dockerfiles/adminpresentation/Dockerfile
Dockerfiles/adminworker/Dockerfile
Dockerfiles/allinone/Dockerfile
Dockerfiles/build/Dockerfile
Dockerfiles/ingest/Dockerfile
Dockerfiles/presentation/Dockerfile
Dockerfiles/worker/Dockerfile

With these changes the base image is changed from `openjdk:8-jdk-alpine` to `alpine:3.5`. Directly using the Alpine images gives more control what version we are using. Alpine version 3.5 now includes every required package in the default repositories configuration. Loading packages from `edge` is no longer necessary, which caused trouble between packages as dependencies were not yet available in specific versions. I assume that staying within the 3.5 repositories will be stable. Additionally, the `openjdk` is rather simple such that it can be included easily.
This PR also updates the Tesseract data repository link.

Upgrade to Alpine 3.5 and Tesseract data

---

Dockerfiles/build/Dockerfile

The build image did not include `nc`, which is used to shut down Opencast properly.

Add missing dependency for build image

---

Dockerfiles/build/Dockerfile
Dockerfiles/build/assets/docker-entrypoint.sh
README.md
docker-compose/README.md
docker-compose/docker-compose.allinone.hsql.yml
docker-compose/docker-compose.allinone.mariadb.yml
docker-compose/docker-compose.build.yml
docker-compose/docker-compose.multiserver.mariadb.yml

Updates docker-compose files to version 3 and makes `HOSTIP` optional by using Docker's service discovery ability.

Update docker-compose files

---

Dockerfiles/admin/assets/docker-entrypoint.sh
Dockerfiles/admin/assets/scripts/helper.sh
Dockerfiles/adminpresentation/assets/docker-entrypoint.sh
Dockerfiles/adminpresentation/assets/scripts/helper.sh
Dockerfiles/adminworker/assets/docker-entrypoint.sh
Dockerfiles/adminworker/assets/scripts/helper.sh
Dockerfiles/allinone/assets/docker-entrypoint.sh
Dockerfiles/allinone/assets/scripts/helper.sh
Dockerfiles/build/assets/bin/oc_install
Dockerfiles/build/assets/build/docker-entrypoint.sh
Dockerfiles/build/assets/build/scripts/helper.sh
Dockerfiles/ingest/assets/docker-entrypoint.sh
Dockerfiles/ingest/assets/scripts/helper.sh
Dockerfiles/presentation/assets/docker-entrypoint.sh
Dockerfiles/presentation/assets/scripts/helper.sh
Dockerfiles/worker/assets/docker-entrypoint.sh
Dockerfiles/worker/assets/scripts/helper.sh

This PR allows for two things:
1. Only mount a subset of configuration files
2. Used placeholder in custom configuration files will also be replaced by environment variables

Run variable replacement for custom configuration files

---

.travis.yml

The package `docker-engine` is now replaced by `dcoker-ce`.

Update Travis CI script

---

Dockerfiles/build/assets/bin/oc_install

The installation script (oc_install) changes the build folder permission, because the permission is not reset (oc_uninstall) building opencast will fail.
> Failed to create assembly: Error creating assembly archive bin: ../build/opencast-* is not writable.
This patch resets the build folder permission.

restores build folder permission

---

Dockerfiles/build/assets/bin/oc_install
Dockerfiles/build/assets/bin/oc_uninstall

Truncating the installation folder allows it to be mounted on the Docker host.

Truncate installation folder instead of deleting it

---

Dockerfiles/admin/assets/docker-entrypoint.sh
Dockerfiles/admin/assets/scripts/helper.sh
Dockerfiles/adminpresentation/assets/docker-entrypoint.sh
Dockerfiles/adminpresentation/assets/scripts/helper.sh
Dockerfiles/adminworker/assets/docker-entrypoint.sh
Dockerfiles/adminworker/assets/scripts/helper.sh
Dockerfiles/allinone/assets/docker-entrypoint.sh
Dockerfiles/allinone/assets/scripts/helper.sh
Dockerfiles/build/assets/build/docker-entrypoint.sh
Dockerfiles/build/assets/build/scripts/helper.sh
Dockerfiles/ingest/assets/docker-entrypoint.sh
Dockerfiles/ingest/assets/scripts/helper.sh
Dockerfiles/migration/assets/docker-entrypoint.sh
Dockerfiles/migration/assets/scripts/helper.sh
Dockerfiles/presentation/assets/docker-entrypoint.sh
Dockerfiles/presentation/assets/scripts/helper.sh
Dockerfiles/worker/assets/docker-entrypoint.sh
Dockerfiles/worker/assets/scripts/helper.sh
README.md

Adds a `<var_FILE>` variant for these variables:
```
ORG_OPENCASTPROJECT_SECURITY_ADMIN_PASS
ORG_OPENCASTPROJECT_SECURITY_DIGEST_PASS
ORG_OPENCASTPROJECT_DB_JDBC_PASS
ACTIVEMQ_BROKER_PASSWORD
```
This allows to set sensitive environment variables indirect by the contents of a file.
Fixes #98

Add ability to pass secret environment variables by file

---

docker-compose/assets/opencast-ddl.sql
docker-compose/docker-compose.multiserver.mariadb.yml

This is an improvement to the docker compose script made by @mtneug add some explicit declaration and improvements for the database. This PR solves #109 and #110. 
- Database Changes
- Change of SQL to Opencast 7.x script.
~~- SQL entry point explicit declaration~~
- Increase of database wait timeout from 600 to 28800
~~- Network Changes~~
~~- Aliases for docker network now with an explicit declaration~~
~~- Port 3306 no declared outside to avoid host conflicts.~~
~~Docker Initialization~~
~~- Opencast nodes will wait for ActiveMQ and MariaDB containers to be ready before they start to be deployed.~~

Improve of docker-compose multisrv

---

Dockerfiles/admin/assets/docker-healthcheck.sh
Dockerfiles/adminpresentation/assets/docker-healthcheck.sh
Dockerfiles/adminworker/assets/docker-healthcheck.sh
Dockerfiles/allinone/assets/docker-healthcheck.sh
Dockerfiles/ingest/assets/docker-healthcheck.sh
Dockerfiles/migration/assets/docker-healthcheck.sh
Dockerfiles/presentation/assets/docker-healthcheck.sh
Dockerfiles/worker/assets/docker-healthcheck.sh

This fixes #112.
`sh` in the base images does not understand the `pipefail` option as was the case with Alpine's shell.

Fix healthcheck script

---

Dockerfiles/build/README.md
README.md
docker-compose/README.md
docker-compose/docker-compose.allinone.h2.yml
docker-compose/docker-compose.allinone.mariadb.yml
docker-compose/docker-compose.build.yml
docker-compose/docker-compose.multiserver.mariadb.yml

Exposed Docker ports are mostly available on localhost on all platforms now. Using localhost also sets the correct URL to the published video.

Simplify docker-compose examples

---

Dockerfiles/build/assets/bin/oc_install

`oc_install` still tried to copy configuration files that no longer exist in the current Opencast versions.
This fixes #121

Fix oc_install command

---

docker-compose/docker-compose.multiserver.mariadb.yml

The download distribution URL needs to be accessible by all Opencast containers and by the Docker host system. This only applies to localhost:8080, i.e. the admin container. This PR changes the download URL back to this instance.
Note that in the best case you use a normal webserver to serve the content or use the presentation node.
This fixes #122

Fix distribution in multiserver example

---

docker-compose/README.md
docker-compose/docker-compose.multiserver.build.yml

This pull requests adds a multi-server docker compose file defining a three node cluster consisting of `build` images for testing distributed setups.  Docs in the Opencast mainline repo will be filed shortly.

Adding multiserver build dockerfile and documentation

---

Dockerfiles/admin/Dockerfile
Dockerfiles/adminpresentation/Dockerfile
Dockerfiles/allinone/Dockerfile
Dockerfiles/build/Dockerfile
Dockerfiles/build/rootfs/usr/local/bin/oc_install
Dockerfiles/ingest/Dockerfile
Dockerfiles/presentation/Dockerfile
Dockerfiles/worker/Dockerfile
rootfs/docker-entrypoint.sh
rootfs/opencast/docker/scripts/activemq.sh
rootfs/opencast/docker/scripts/elasticsearch.sh
rootfs/opencast/docker/scripts/h2.sh
rootfs/opencast/docker/scripts/helper.sh
rootfs/opencast/docker/scripts/jdbc.sh
rootfs/opencast/docker/scripts/opencast.sh

Currently, custom config mounted to `/etc/opencast` is not synced with the running config `/opencast/etc` on changes. This adds a watch background job that syncs those files. `/etc/opencast` is implemented as an overlay over the default Opencast configuration. Those are first merged in a staging area then variables may be replaced after which the files are synced to `/opencast/etc`. Using `rsync` anly necessary copy and delete operations are performed such that Opencast service reconfiguration should be kept to a minimum.
This also ignores folders/symlinks in the custom config that starts with two dots. This is used by Kubernetes when mounting configuration and secrets.

Sync custom config changes with running config

---

docker-compose/docker-compose.allinone.h2+pyca.yml
docker-compose/docker-compose.allinone.h2.yml
docker-compose/docker-compose.allinone.mariadb.yml
docker-compose/docker-compose.allinone.postgres.yml
docker-compose/docker-compose.build.yml
docker-compose/docker-compose.multiserver.build.yml
docker-compose/docker-compose.multiserver.mariadb.yml
docker-compose/docker-compose.multiserver.postgres.yml

This patch adds the mitigation for CVE-2021-44228 to the default
Elasticsearch configuration in the docker-compose files.

Add Elasticsearch Log4Shell Mitigation

---

docker-compose/docker-compose.allinone.h2+pyca.yml
docker-compose/docker-compose.allinone.h2.yml
docker-compose/docker-compose.allinone.mariadb.yml
docker-compose/docker-compose.allinone.postgres.yml
docker-compose/docker-compose.build.yml
docker-compose/docker-compose.multiserver.build.yml
docker-compose/docker-compose.multiserver.mariadb.yml
docker-compose/docker-compose.multiserver.postgres.yml

Opencast switched to OpenSearch examples in the dev container setup. OpenSearch v1 is compatible with Elasticsearch.

Switch to using OpenSearch

---

Makefile

The configured FFmpeg version was not passed as build arg resulting in installing the latest one.

Fix installed FFmpeg version

---

rootfs/docker-entrypoint.sh

When adding custom CA certificates the system and Java stores need to be updated. This patch adds a function for that that is always called during init.

Add function to update certificate authority store on init
